
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Aug 02 14:41:55 CST 2015
//----------------------------------------------------

package com.example.lezs.graficadorfiguras;

/** CUP generated class containing symbol constants. */
public class simbolo {
  /* terminals */
  public static final int rojo = 9;
  public static final int poligono = 7;
  public static final int aparentesis = 16;
  public static final int morado = 13;
  public static final int circulo = 3;
  public static final int coma = 18;
  public static final int numero = 23;
  public static final int por = 19;
  public static final int negro = 15;
  public static final int linea = 6;
  public static final int azul = 8;
  public static final int menos = 22;
  public static final int EOF = 0;
  public static final int dividido = 20;
  public static final int error = 1;
  public static final int cuadrado = 4;
  public static final int verde = 10;
  public static final int graficar = 2;
  public static final int rectangulo = 5;
  public static final int amarillo = 11;
  public static final int mas = 21;
  public static final int naranja = 12;
  public static final int cparentesis = 17;
  public static final int cafe = 14;
}

